clone_folder: c:\gopath\src\github.com\starius\flock

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env

build_script:
  - go get -t github.com/starius/flock
  - go test github.com/starius/flock
